### ISSUE TITLE
Memo integration

### ISSUE THREAD

**Issue by smudge202** [4Com/compose-remoting#1]
As per the sblackler/Memo#20 discussion, looking forward to a PR for the memo work to mull over.  Get to know the code a little better and hopefully make some useful recommendations.

**Comment by sblackler** [comment]
Here is a rough idea of how I envisaged the inbound message pipeline:

![inboundmessagepipeline](https://cloud.githubusercontent.com/assets/775191/7145761/822c8580-e2e6-11e4-9da7-71a7da8dbdfc.png)

And this is a rough outline for the outbound message pipeline:

![outboundmessagepipeline 1](https://cloud.githubusercontent.com/assets/775191/7146056/b5660942-e2e8-11e4-8c21-07a131395314.png)

There are a few other bits to help such as type naming etc. But the above should give you a general idea of what's there and where

**Comment by sblackler** [comment]
#5 refers

**Comment by smudge202** [comment]
Question: Should Compose.Remoting care about events vs other types of message? Or is that the concern of a consumer?

**Comment by sblackler** [comment]
The transports will need to so that they can route properly but otherwise no. That's why on the outline pipeline there is just a single method not two (send as opposed to send/publish).

**Comment by sblackler** [comment]
This can be closed as #5 is merged
