### ISSUE TITLE
Removal of IF DEF for binary serialization?

### ISSUE THREAD

**Issue by sblackler** [4Com/compose-remoting#18]
Currently, the exceptions we have are marked as Serializable to comply with a CA rule. However, this is attribute is not supported on the core frameworks due to the fact Binary serialization itself isnt supported.

The code currently looks like this: 

	using System;
	namespace Compose.Remoting
	{
	#if !SerializationUnsupported
		using System.Runtime.Serialization;
		[Serializable]
	#endif
		public class InvalidMessageException : Exception

Which has the `SerializationUnsupported` constant defined for `netcore45` & `dnxcore50`. There are three options: 

1. Leave the code as is - it's fine
2. Suppress the CA rules in the classes affected and remove the constant
3. Remove the code that's not compatible and let the CA throw

I'm currently leaning towards option 2 as that will leave the code cleaner imo.

Thoughts: @smudge202 @mattridgway @herecydev ?

**Comment by herecydev** [comment]
I guess a good question would be how are other exceptions done. The base `Exception` class should be serializable; so if its not possible in core frameworks what do they intend to do?

Ideally, and what I would expect to happen, is that code analysis would have different rules for different frameworks. As you can see, you can't blanket rule all of the things.

**Comment by smudge202** [comment]
It's worth noting, it's _binary_ serialization that is not supported. Other serialization types are still available (so naming of the directive might want to better reflect that?).

I'm off out but will take another look at this later.
