### ISSUE TITLE
Upgrade test projects to use TestHelpers

### ISSUE THREAD

**Issue by sblackler** [4Com/compose-remoting#6]
As per the title, the TestHelpers now appear on NuGet. I think that we should upgrade to these before the first release

**Comment by herecydev** [comment]
Say testhelpers again. Say it 1 more time! I dare you, I double dare you!

**Comment by smudge202** [comment]
I had a look at this, this morning. Was going to defer until TestHelpers support data tests: herecydev/testattributes#6.
