### ISSUE TITLE
General architecture review

### ISSUE THREAD

**Issue by sblackler** [4Com/compose-remoting#8]
The current process is add serialization/compression/encryption and associated properties to the message as the message leaves the sending application. The receiving application would then take the message and inspect the properties of the message and use the right provider to decrypt/decompress/de-serialize based on what is registered in the receiving application.

This is using a form of service location but not using an IOC container directly. Granted not ideal, but one of the main goals behind the project was to provide per message encryption/compression/serialization.

This design has caused a number of issues to be raised: 

1. The use of magic strings
2. Interface segregation
3. Service Location

If we are happy to keep this service location style pattern, then we can clean up the use of the magic strings by offloading this to the extension and providing the appropriate properties on the `Message` class, for example.  Otherwise, we will need to look at other patterns eg: visitor in order to achieve this. 

Interface segregation can happen so long as the correct provider can be inferred for encryption/serialisation/compression (assuming the default pipelines).

Personally, I am unsure whether the initial architecture I wrote is correct or whether there is another better suited pattern. Feedback greatly welcome.

Links to the issues that this issue summarises: 

https://github.com/sblackler/compose-remoting/issues/36
https://github.com/sblackler/compose-remoting/issues/28
https://github.com/sblackler/compose-remoting/issues/10

**Comment by sblackler** [comment]
Summary of discussions between @smudge202 @mattridgway and myself:

- The inbound/outbound pipelines can ditch nearly all of the factories, favouring a the use of transitions with a transition scope within the main compose library (feature pending)
- `InboundMessagePipeline` will now inherit from `IObservable<Message>` taking over the role from `DefaultTransportMessageObserver`
- Given the above we should now be able to separate the interfaces on the providers so we abide by the SRP.

This streamlines the original architecture by removing the service location based on the new information provided by @smudge202 on how compose deals with dependencies. I will tackle this before #7

**Comment by sblackler** [comment]
Anything else that people want to review on this before I start looking at pushing this forward?

**Comment by smudge202** [comment]
I'm sure there will be opportunities to do further passes on architecture at later stages.
